#' Function to compile GOTM-FABM
#'
#' This function compiles GOTM-FABM with FABM source code generated by gen_fabm_code().
#' It assumes that you allready have run cmake within the buiold directory
#' @param build_dir build directory
#' @param src_dir source directory. should be the FABM directory within the GOTM source directory
#' @param fabm_file forthran source file for FABM created by gen_fabm_code()
#' @keywords FABM, GOTM, compile
#' @author Johannes Feldbauer
#' @export
#' @examples
#' \dontrun{
#' library(readODS)
#' library(rodeoFABM)
#'
#' # copy example ods file
#' example_model <- system.file("extdata//", package= 'rodeoFABM')
#' dir.create('example') # Create example folder
#' file.copy(from = example_model, to = 'example',recursive = TRUE)
#' setwd('example') # Change working directory to example folder
#'
#' # read in example ods file
#' odf_file <- "simple_model.ods"
#' vars <- read_ods(odf_file,1)
#' pars <- read_ods(odf_file,2)
#' funs <- read_ods(odf_file,3)
#' pros <- read_ods(odf_file,4)
#' stoi <- read_ods(odf_file,5)
#'
#' # generate fabm code
#' gen_fabm_code(vars,pars,funs,pros,stoi,"simple_model.f90",diags = TRUE)
#' # build GOTM
#' build_GOTM(build_dir = "../build/",fabm_file = f90_file,
#'            src_dir = "../gotm/extern/fabm/src/models/tuddhyb/rodeo/")
#' }
#'
build_GOTM <- function(build_dir,src_dir,fabm_file){

  # name of the fortran file within the FABM directory
  src_file = "rodeo.f90"

  # Set original working directory
  oldwd <- getwd()

  # this way if the function exits for any reason, success or failure, wd are reset:
  on.exit({
    setwd(oldwd)
  })

  # copy FABM file to source directory
  cat("copying file ",fabm_file," to ",src_dir,"\n")
  file.copy(fabm_file,paste0(src_dir,"/",src_file),overwrite = TRUE)

  # complie
  setwd(build_dir)
  cat("compiling \n\n")
  system2("make")

  # copy new gotm executable to original directory
  file.copy("gotm",paste0(oldwd,"/gotm"),overwrite = TRUE)
  cat("finished \n")

}


